> ### **Assignment 2 - Numpy Array Operations** 
>
> This assignment is part of the course ["Data Analysis with Python: Zero to Pandas"](http://zerotopandas.com). The objective of this assignment is to develop a solid understanding of Numpy array operations. In this assignment you will:
> 
> 1. Pick 5 interesting Numpy array functions by going through the documentation: https://numpy.org/doc/stable/reference/routines.html 
> 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 3 examples for each function). Use your imagination to come up with interesting and unique examples.
> 3. Upload this notebook to your Jovian profile using `jovian.commit` and make a submission here: https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-2-numpy-array-operations
> 4. (Optional) Share your notebook online (on Twitter, LinkedIn, Facebook) and on the community forum thread: https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575 . 
> 5. (Optional) Check out the notebooks [shared by other participants](https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575) and give feedback & appreciation.
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.
>
> Try to give your notebook a catchy title & subtitle e.g. "All about Numpy array operations", "5 Numpy functions you didn't know you needed", "A beginner's guide to broadcasting in Numpy", "Interesting ways to create Numpy arrays", "Trigonometic functions in Numpy", "How to use Python for Linear Algebra" etc.
>
> **NOTE**: Remove this block of explanation text before submitting or sharing your notebook online - to make it more presentable.


# Numpy Library


### Introduction

Numpy stands for Numerical Python. It is a library consisting of multidimensional array objects and a collection of routines for proccessing of arrays. We can perform mathematical and logical operations and manipulation on arrays using this library. Below are few basic Numpy fucntions

- numpy.arange([start, ]stop, [step, ]dtype=None)
- numpy.transpose(a, axes=None)
- numpy.ravel(a, order='C')
- numpy.vstack(tup)
- numpy.mean(a, axis=None, dtype=None, out=None, keepdims=<no value>)


The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [18]:
!pip install jovian --upgrade -q

In [19]:
import jovian

In [23]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "bikashacharaya10/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/bikashacharaya10/numpy-array-operations


'https://jovian.ml/bikashacharaya10/numpy-array-operations'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [2]:
import numpy as np

In [ ]:
# List of functions explained 
function1 = np.arange()
function2 = np.transpose()
function3 = np.ravel()
function4 = np.vstack()
function5 = np.mean()

## Function 1- np.arange()

NumPy arange() is one of the array creation routines based on numerical ranges. It creates an instance of ndarray with evenly spaced values and returns the reference to it. And stop is the number that defines the end of the array and isn't included in the array.

In [7]:
# Example 1 - working
num=np.arange(1,300,3)
num

array([  1,   4,   7,  10,  13,  16,  19,  22,  25,  28,  31,  34,  37,
        40,  43,  46,  49,  52,  55,  58,  61,  64,  67,  70,  73,  76,
        79,  82,  85,  88,  91,  94,  97, 100, 103, 106, 109, 112, 115,
       118, 121, 124, 127, 130, 133, 136, 139, 142, 145, 148, 151, 154,
       157, 160, 163, 166, 169, 172, 175, 178, 181, 184, 187, 190, 193,
       196, 199, 202, 205, 208, 211, 214, 217, 220, 223, 226, 229, 232,
       235, 238, 241, 244, 247, 250, 253, 256, 259, 262, 265, 268, 271,
       274, 277, 280, 283, 286, 289, 292, 295, 298])

This function is similar to the range() function. It will generated the element between 1 to 300 (excluding 100) with interval of 3. Here, the default dtype will be int64.

In [8]:
# Example 2 -working
num1=np.arange(10,200,5.5, dtype = float)
num1

array([ 10. ,  15.5,  21. ,  26.5,  32. ,  37.5,  43. ,  48.5,  54. ,
        59.5,  65. ,  70.5,  76. ,  81.5,  87. ,  92.5,  98. , 103.5,
       109. , 114.5, 120. , 125.5, 131. , 136.5, 142. , 147.5, 153. ,
       158.5, 164. , 169.5, 175. , 180.5, 186. , 191.5, 197. ])


The above example will return an array having values starting from 10 upto 200 (excluding 200) in the interval of 5..5 and the data type of the values in the returned matrix is float because we used "dtype=float".

In [9]:
# Example 3 - breaking (to illustrate when it breaks)
np.arange()

TypeError: arange() missing required argument 'start' (pos 1)

In above example, We are not passing any parameter.

This function is similar to range() function which we need to pass parameter as a starting value and ending value and interval is optional.

In [25]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "bikashacharaya10/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/bikashacharaya10/numpy-array-operations


'https://jovian.ml/bikashacharaya10/numpy-array-operations'

## Function 2 - np.transpose()

Reverse or permute the axes of an array; returns the modified array. For an array a with two axes, transpose(a) gives the matrix transpose.


In [13]:
# Example 1 - working

arr=np.arange(60).reshape(6,10)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [14]:
arr.shape

(6, 10)

In [15]:
arr.transpose()

array([[ 0, 10, 20, 30, 40, 50],
       [ 1, 11, 21, 31, 41, 51],
       [ 2, 12, 22, 32, 42, 52],
       [ 3, 13, 23, 33, 43, 53],
       [ 4, 14, 24, 34, 44, 54],
       [ 5, 15, 25, 35, 45, 55],
       [ 6, 16, 26, 36, 46, 56],
       [ 7, 17, 27, 37, 47, 57],
       [ 8, 18, 28, 38, 48, 58],
       [ 9, 19, 29, 39, 49, 59]])

In [16]:
arr.transpose().shape

(10, 6)

This np.transpose() function will re-arrange the dimension in Reverse order.
1st we created 2D array with shape of 6 rows and 10 columns. After initialized transpose() function, the array re-arrange into 10 rows and 6 columns.

In [17]:
# Example 2 - working
arr=np.arange(60).reshape(6,5,2)
arr

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49]],

       [[50, 51],
        [52, 53],
        [54, 55],
        [56, 57],
        [58, 59]]])

In [18]:
arr.shape

(6, 5, 2)

In [19]:
arr.transpose()

array([[[ 0, 10, 20, 30, 40, 50],
        [ 2, 12, 22, 32, 42, 52],
        [ 4, 14, 24, 34, 44, 54],
        [ 6, 16, 26, 36, 46, 56],
        [ 8, 18, 28, 38, 48, 58]],

       [[ 1, 11, 21, 31, 41, 51],
        [ 3, 13, 23, 33, 43, 53],
        [ 5, 15, 25, 35, 45, 55],
        [ 7, 17, 27, 37, 47, 57],
        [ 9, 19, 29, 39, 49, 59]]])

In [20]:
arr.transpose().shape

(2, 5, 6)

This np.transpose() function will re-arrange the dimension in Reverse order.
1st we created 3D array with shape of 6 rows, 5 array and 2 columns. After initialized transpose() function, the array re-arrange into 2 rows, 5 array and 6 columns.

In [21]:
# Example 3 - breaking (to illustrate when it breaks)
arr=np.arange(60).reshape(6,10)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [22]:
np.transpose(arr,axes=(1,0,1))

ValueError: axes don't match array


The syntax of transpose is  numpy.transpose(a, axes=None). If we created 2D array and want to performs transpose() function on it. But in 2D array we cannot pass np.transpose(arr,axes=(1,0,1)). It return TypeError and ValueError: axes dont match array. It means axes and array is not matching. We need to pass equal axes for  array.
So, the perfect code : np.transpose(arr,axes=(1,0)). It have total number of array equals to total number of axes.
For instance, 2D array contain 2 axes as well as 3D array contain 3 axes. 


The transpose() function is used to permute the dimensions of an array. Input array. By default, reverse the dimensions, otherwise permute the axes according to the values given.

In [26]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "bikashacharaya10/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/bikashacharaya10/numpy-array-operations


'https://jovian.ml/bikashacharaya10/numpy-array-operations'

## Function 3 - np.ravel()

The numpy module of Python provides a function called numpy. ravel, which is used to change a 2-dimensional array or a multi-dimensional array into a contiguous flattened array. The returned array has the same data type as the source array or input array.

In [24]:
# Example 1 - working
num=np.array([
    [[1,2,3],[3,4,5]],
    [[6,7,8],[9,10,11]]
])
num

array([[[ 1,  2,  3],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [25]:
num.ravel()

array([ 1,  2,  3,  3,  4,  5,  6,  7,  8,  9, 10, 11])

This ravel() function will return or convert 2-D or multidimensional array into contiguous flattened array or 1-D array.
Here I input as a 2-D array and I initalized ravel(). It return  array([ 1,  2,  3,  3,  4,  5,  6,  7,  8,  9, 10, 11]) this as a output.

In [26]:
# Example 2 - working
num1=np.array([
    [10,20],
    [30,40]
])
num1

array([[10, 20],
       [30, 40]])

In [27]:
num1.ravel()

array([10, 20, 30, 40])

In [28]:
num1.ravel(order="F")

array([10, 30, 20, 40])

Here, In ravel() function while passing parameter order="F" .‘F’ means to index the elements in column-major, Fortran-style order, with the first index changing fastest, and the last index changing slowest i.e It perform columns wise operations.

In [29]:
# Example 3 - breaking (to illustrate when it breaks)
num3=np.array([
    [100,200],
    [300,400]
])
num3

array([[100, 200],
       [300, 400]])

In [30]:
num3.ravel(order="B")

ValueError: order must be one of 'C', 'F', 'A', or 'K' (got 'B')

In this above code, It return ValueError due to passing wrong parameter .The "order" only contain 'C','F','A','K'. Each order have different function on it. Check out more in numpy documentation.
https://numpy.org/doc/stable/reference/generated/numpy.ravel.html

The ravel() function is used to create a contiguous flattened array. A 1-D array, containing the elements of the input, is returned. A copy is made only if needed. 

In [27]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "bikashacharaya10/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/bikashacharaya10/numpy-array-operations


'https://jovian.ml/bikashacharaya10/numpy-array-operations'

## Function 4- np.vstack()

The vstack() function is used to stack arrays in sequence vertically (row wise).
This is equivalent to concatenation along the first axis after 1-D arrays of shape (N,) have been reshaped to (1,N).
This function makes most sense for arrays with up to 3 dimensions. 

In [32]:
# Example 1 - working
a=np.arange(5)
b=np.arange(5)

In [33]:
a

array([0, 1, 2, 3, 4])

In [34]:
b

array([0, 1, 2, 3, 4])

In [35]:
np.vstack((a,b))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

Here in above example, two variable are created a and b. Both are having 1-D array. Now with the function vstack(), it merge both variable (a,b) of 1-D array and return 2-D array. 

In [5]:
# Example 2 - working
a=np.array([
    [1,2],[3,4]
])
b=np.array([
    [5,6]
])

In [37]:
a

array([[1, 2],
       [3, 4]])

In [38]:
b

array([[5, 6]])

In [10]:
np.vstack((a,b))


array([[1, 2],
       [3, 4],
       [5, 6]])

Here in above example, two variable are created a and b. Both are having 2-D array. Now with the function vstack(), it merge both variable and return 2-D array. 

In [42]:
# Example 3 - breaking (to illustrate when it breaks)
a=np.arange(5)
a

array([0, 1, 2, 3, 4])

In [45]:
b=np.array([
    [1,2],[3,4] ])
b

array([[1, 2],
       [3, 4]])

In [46]:
np.vstack((a,b))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 5 and the array at index 1 has size 2

Here we initalized two variable a & b. The variable a is 1-D array and b is 2-D array. But it return error while using vstack() function. Because both variable should be at same dimension otherwise vstack() function will return error.

vstack() function is used to stack the sequence of input arrays vertically to make a single array. 

In [28]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "bikashacharaya10/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/bikashacharaya10/numpy-array-operations


'https://jovian.ml/bikashacharaya10/numpy-array-operations'

## Function 5 - np.mean()

The numpy. mean() function is used to compute the arithmetic mean along the specified axis. This function returns the average of the array elements. By default, the average is taken on the flattened array. Else on the specified axis, float 64 is intermediate as well as return values are used for integer inputs.


In [4]:
# Example 1 - working
a = np.array([[100, 200, 300, 400, 500, 600,700,800,900]])
a.mean()

500.0

Arithmetic mean is the sum of elements along an axis divided by the number of elements. The numpy. mean() function returns the arithmetic mean of elements in the array. If the axis is mentioned, it is calculated along it.

In [8]:
# Example 2 - working
a1 = np.array([[1, 2], 
                [3, 4]])

a2 = np.array([[3, 4], 
                [5, 6]])


In [9]:
c=np.mean(a1+a2)
c

7.0

This example is finding the determinat and the mean of the matrix a1 and matrix a2 which is 7



In [13]:
# Example 3 - breaking (to illustrate when it breaks)
a3 = np.array([[1, 2, 4], 
                [4, 5 ,6]])

In [15]:
a4 = np.array([[7, 8, 9,5], 
                [2, 3, 4, 5]])

In [16]:
c=np.mean(a3+a4)
c

ValueError: operands could not be broadcast together with shapes (2,3) (2,4) 

The above Matrix a3 and a4 : finds the mean of the matrix but the code will break because the shape of matrix are not the same.

The np. mean() function is generally used to get the average of all values in a dataset. We can apply this function with a logical statement to get the percent of values that satisfy the logical statement

In [29]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "bikashacharaya10/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/bikashacharaya10/numpy-array-operations


'https://jovian.ml/bikashacharaya10/numpy-array-operations'

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..


## Conclusion

Summarize what was covered in this notebook, and where to go next

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* ...

In [30]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-array-operations


'https://jovian.ml/aakashns/numpy-array-operations'